# Generated by Django 3.2.7 on 2021-09-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210917_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Mobile Number'),
        ),
    ]
