# Generated by Django 3.2.7 on 2021-10-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20211007_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price_with_discount',
            field=models.PositiveIntegerField(null=True, verbose_name='total_price_with_discount '),
        ),
    ]
