# Generated by Django 3.2.7 on 2021-10-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_total_price_with_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price_with_discount',
        ),
    ]
